export const SERVER_BASE_URL_DEVELOPMENT = 'http://localhost:5000/api/v1';
export const PRO_SHOP_CART_ITEMS_KEY = 'PRO_SHOP_CART_ITEMS_KEY';
export const PRO_SHOP_USER_INFO_KEY = 'PRO_SHOP_USER_INFO_KEY';
export const PRO_SHOP_TOKEN_KEY = 'PRO_SHOP_TOKEN_KEY';
export const PRO_SHOP_SHIPPING_ADDRESS_KEY = 'PRO_SHOP_SHIPPING_ADDRESS_KEY';
export const PRO_SHOP_PAYMENT_METHOD_KEY = 'PRO_SHOP_PAYMENT_METHOD_KEY';